app:
  name: optipie-user-management-api
  environment: staging
  is_local_development: true
  timeout: 3000 #ms
  web_hook_keys:
    membership_started: xxx
    membership_updated: xxx
    membership_cancelled: xxx
aws:
  dynamodb:
    membership:
      table_name: membership
    analytics:
      table_name: analytics
